spring.application.name=discovery-server
server.port=${DISCOVERY_SERVER_PORT:8761}

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}

spring.cloud.config.enabled=${CONFIG_ENABLED:false}
spring.config.import=optional:configserver:${CONFIG_URI:http://localhost:8762}

management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true

spring.cloud.compatibility-verifier.enabled=false
