CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    slug VARCHAR(120) NOT NULL,
    active BOOLEAN NOT NULL
);

ALTER TABLE categories
    ADD CONSTRAINT uk_categories_slug UNIQUE (slug);

CREATE INDEX idx_categories_slug ON categories (slug);

CREATE TABLE products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    description VARCHAR(1000),
    price NUMERIC(19, 2) NOT NULL,
    stock_quantity INTEGER NOT NULL,
    sku VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL,
    category_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

ALTER TABLE products
    ADD CONSTRAINT uk_products_sku UNIQUE (sku);

ALTER TABLE products
    ADD CONSTRAINT fk_products_category
    FOREIGN KEY (category_id)
    REFERENCES categories (id);

CREATE INDEX idx_products_category_id ON products (category_id);
CREATE INDEX idx_products_sku ON products (sku);

CREATE TABLE product_images (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url VARCHAR(500) NOT NULL,
    main_image BOOLEAN NOT NULL,
    product_id BIGINT NOT NULL
);

ALTER TABLE product_images
    ADD CONSTRAINT fk_product_images_product
    FOREIGN KEY (product_id)
    REFERENCES products (id);

CREATE INDEX idx_product_images_product_id ON product_images (product_id);
