
spring.application.name=config-server
server.port=8762

spring.profiles.active=local
spring.profiles.include=native
spring.cloud.config.server.native.search-locations=classpath:/config
spring.cloud.compatibility-verifier.enabled=false
management.endpoints.web.exposure.include=*

eureka.instance.hostname=config-server
