server.port=${API_GATEWAY_PORT:8760}

eureka.client.service-url.defaultZone=${EUREKA_URI:http://localhost:8761/eureka}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

spring.cloud.gateway.server.webflux.metrics.enabled=true
spring.cloud.gateway.server.webflux.httpclient.connect-timeout=${GATEWAY_CONNECT_TIMEOUT_MS:2000}
spring.cloud.gateway.server.webflux.httpclient.response-timeout=${GATEWAY_RESPONSE_TIMEOUT:5s}
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/ecommerce}

spring.cloud.gateway.server.webflux.routes[0].id=product-service-products
spring.cloud.gateway.server.webflux.routes[0].uri=lb://product-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/v1/products/**

spring.cloud.gateway.server.webflux.routes[1].id=product-service-categories
spring.cloud.gateway.server.webflux.routes[1].uri=lb://product-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/api/v1/categories/**

gateway.rate-limiter.enabled=${GATEWAY_RATE_LIMIT_ENABLED:false}
gateway.rate-limiter.replenish-rate=${GATEWAY_RATE_LIMIT_REPLENISH_RATE:20}
gateway.rate-limiter.burst-capacity=${GATEWAY_RATE_LIMIT_BURST_CAPACITY:40}
