spring.application.name=product-service
server.port=8763

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce-microservice
spring.datasource.username=postgres
spring.datasource.password=12345
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true