CREATE TABLE cart.carts (
    id VARCHAR(36) PRIMARY KEY,
    customer_id VARCHAR(120) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_carts_customer_id ON cart.carts (customer_id);
CREATE INDEX idx_carts_customer_status ON cart.carts (customer_id, status);

CREATE TABLE cart.cart_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id VARCHAR(36) NOT NULL,
    product_id BIGINT NOT NULL,
    product_name VARCHAR(150) NOT NULL,
    unit_price NUMERIC(19, 2) NOT NULL,
    quantity INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

ALTER TABLE cart.cart_items
    ADD CONSTRAINT fk_cart_items_cart
    FOREIGN KEY (cart_id)
    REFERENCES cart.carts (id)
    ON DELETE CASCADE;

ALTER TABLE cart.cart_items
    ADD CONSTRAINT uk_cart_items_cart_product UNIQUE (cart_id, product_id);

CREATE INDEX idx_cart_items_cart_id ON cart.cart_items (cart_id);
CREATE INDEX idx_cart_items_product_id ON cart.cart_items (product_id);
